# Generated by Django 4.2 on 2024-06-28 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_loanapplication_registration_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='registration_address',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^г\\.?\\s*[А-ЯЁ][а-яё]+\\s*,?\\s*ул\\.?\\s*[А-ЯЁа-яё0-9]+\\s*,?\\s*д\\.?\\s*\\d+')], verbose_name='Адрес регистрации'),
        ),
    ]
