# Generated by Django 4.2 on 2024-06-28 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_loanapplication_registration_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='passport_number',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', message='Введите корректный номер паспорта.')], verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='passport_series',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', message='Введите корректную серию паспорта.')], verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='registration_address',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^г\\.?\\s*[А-ЯЁ][а-яё]+\\s*,?\\s*ул\\.?\\s*[А-ЯЁа-яё0-9]+\\s*,?\\\n                                                s*д\\.?\\s*\\d+', message='формат ввода: г. ул. д.')], verbose_name='Адрес регистрации'),
        ),
    ]
